### ISSUE TITLE
Build Process and Where Files need to be placed in Directories

### ISSUE THREAD

**Issue by ghost** [rfporter/Robust-CSV#1]
I can't find any built VI Package files so I guess I need to build it myself.

When I clone the project to my computer and open the .vipb file it gives me this error message.
![image](https://user-images.githubusercontent.com/33966941/65347837-7a552d00-dba5-11e9-983a-bc12871473a6.png)
When I press OK, I then see that the Source Directory is not the same as where I cloned the project. It appears I have to mess around with the location of the .vipb file and the project. This is the directory structure that I am using:
```
Desktop\builds:
|   Robust CSV.vipb
|   
\---Robust CSV
    |   lava_lib_robust_csv-1.1.0.5.vip
    |   
    \---Source Distribution
        |   .gitignore
        |   dir.mnu
        |   Flatten to CSV Record.vi
        |   LICENSE
        |   Parse CSV String.vi
        |   Read CSV File.vi
        |   README.md
        |   ReadMe.txt
        |   Robust CSV.aliases
        |   Robust CSV.lvlib
        |   Robust CSV.lvlps
        |   Robust CSV.lvproj
        |   Write CSV File.vi
        |   Write CSV File_1D.vi
        |   Write CSV File_2D.vi
        |   
        \---Examples
                MOCK_DATA.csv
                Robust CSV Example Usage.vi
```
Can this be documented or made clearer in some way?

**Comment by rfporter** [comment]
Thanks for bringing this to my attention.
You can now find the VI package in the v1.1.0 release.

In order to build your own VI package, you need to clone the project, then build the source distribution (already setup in the lvproj build specs). Once the source distribution is built, then use the .vipb file to build the VI package from the source distribution.

Note that if you open the .vipb file without building the source distribution first, the pallets will be broken. So its not a good idea to save changes to the .vipb file without having the source distribution in place.

Of course, I should document this more clearly in the readme.md. Just need to find some time to do it.

**Comment by ghost** [comment]
Thanks. You might mention this dialog in the documentation too. I guess you're building this in LV 8.6 so it is compatible for everyone? But it shouldn't normally make a difference for someone to build in a later version of LV for their own purposes?
![image](https://user-images.githubusercontent.com/33966941/65357317-59e49d00-dbbc-11e9-9d09-8f30c170f64d.png)

**Comment by rfporter** [comment]
Now building on LabVIEW 2012 or later. Build instructions are in readme.md
